### ISSUE TITLE
 no connection: server outdated

### ISSUE THREAD

**Issue by Den4ik1992** [tristanmorgan/bedrock-box#1]
Hey tristanmorgan,

i get an error when trying to access the server:
"no connection: server outdated" the game on the android phone is up to date.

How i can fix it ?

I like your work very much keep it up ;)

//EDIT

Sry my mistake: I didn't install the latest version.

**Comment by tristanmorgan** [comment]
Glad it all worked out. I should automate it, but I build when I see [LomotHo's repo](http://github.com/LomotHo/minecraft-bedrock/) being updated.
